### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ghost** [jayphelps/wasm-anyref-demo#2]
Thanks for publishing this! 
I'm curious about the interface of Wasm and host environments. Especially performance and code size.
I tried running `npm install` on macOS 10.15.7 using node @14.17.3 but node-gyp failed:
```
$ npm install

> fsevents@1.2.9 install /Users/eli/foss/wasmlearning/wasm-anyref-demo/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@14.17.3 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
```
I don't expect you to fix this but wanted to post in case anyone else runs into this.

**Comment by jayphelps** [comment]
Usually this is caused by not having Xcode stuff installed, which is required to build native node addons. 

Try:

```bash
xcode-select --install
```

https://github.com/nodejs/node-gyp#on-macos

**Comment by ghost** [comment]
@jayphelps thanks for the tip!
The funny thing is I have developer tools installed:
```
 xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
I've run into this issue before and believe it may relate to using volta to manage my node.js installation combined with how precompiled node-gyp binaries are made available.

Turns out `yarn install` successfully installed the dependencies but `npm start` failed.
So rather than chase toolchain errors I simply pinned node 12.x to the package.json. I believe that preserves the intent of this demo better.

**Comment by jayphelps** [comment]
![image](https://user-images.githubusercontent.com/762949/128399835-e97b528d-82ca-40d4-8917-774c21824098.png)

Weird! I tried node 14.17.3 with a fresh clone, and it worked fine. Same with node 15 and 16.

**Comment by ghost** [comment]
Huh. I wager it is my machine. So I'll close.
For future travelers:
`volta pin node@12 && npm install`
